{% set name = "brain-isotopic-distribution" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab0b7d9b7394d969b9835b54dc9ed7b4d0a593c408ec8aa2a35d413a0948ea44

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - brainpy
    - brainpy._c
    - brainpy.test

about:
  home: https://github.com/mobiusklein/brainpy
  license: Apache Software
  license_family: APACHE
  license_file:
  summary: Fast and efficient theoretical isotopic profile generation
  doc_url: http://mobiusklein.github.io
  dev_url: https://github.com/mobiusklein/brainpy

extra:
  recipe-maintainers:
    - bgruening
